# Generated by Django 3.2 on 2021-12-28 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('employment_date', models.DateField()),
                ('post', models.CharField(choices=[(5, 'Работник'), (4, 'Старший работник'), (3, 'Начальник'), (2, 'Зам. Директора'), (1, 'Директор')], max_length=255)),
                ('salary', models.PositiveIntegerField()),
                ('chief', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worker.worker')),
            ],
        ),
    ]
