# Generated by Django 3.2 on 2021-12-28 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='chief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worker.worker'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='post',
            field=models.CharField(choices=[('Worker', 'Работник'), ('Older Worker', 'Старший работник'), ('Chief', 'Начальник'), ('ExDirector', 'Зам. Директора'), ('Director', 'Директор')], max_length=255),
        ),
    ]
