# Generated by Django 3.2 on 2021-12-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_auto_20211228_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='post',
            field=models.CharField(choices=[('Работник', 'Работник'), ('Старший работник', 'Старший работник'), ('Начальник', 'Начальник'), ('Зам. Директора', 'Зам. Директора'), ('Директор', 'Директор')], max_length=255),
        ),
    ]
